{% set name = "snowflake-snowpark-python" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/snowflake-snowpark-python-{{ version }}.tar.gz
  sha256: 62d3d353fb48149a3cb256331078257cf51e122f8c8b5f38a686a364f845c467

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.11
    - pip
  run:
    - python >=3.8,<3.11
    - setuptools >=40.6.0
    - wheel
    - cloudpickle >=1.6.0,<=2.0.0
    - snowflake-connector-python >=3.2.0,<4.0.0
    - typing-extensions >=4.1.0,<5.0.0
    - pyyaml

test:
  imports:
    - snowflake.snowpark
    - snowflake.snowpark._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.snowflake.com/
  summary: Snowflake Snowpark for Python
  dev_url: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sfc-gh-yixie
    - sfc-gh-achandrasekaran
    - sfc-gh-mkeller
