{% set name = "snowflake-snowpark-python" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: da982696597057fae66a76ebea8b7a9bc8d05a5f402eba0cbd6c3a8267457208

build:
  skip: true  # [py<38 or py>311]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
    # Snowpark IR
    - protobuf ==3.20.1  # [py<=310]
    - protobuf ==4.25.3  # [py>310]
    - mypy-protobuf
  run:
    - python
    - setuptools >=40.6.0
    - wheel
    - cloudpickle >=1.6.0,<=2.2.1,!=2.1.0,!=2.2.0  # [py<311]
    - cloudpickle >=2.2.1,<3.0.0  # [py==311]
    - snowflake-connector-python >=3.12.0,<4.0.0
    - typing-extensions >=4.1.0,<5.0.0
    - pyyaml
    - protobuf >=3.20,<6
    - tzlocal

test:
  imports:
    - snowflake.snowpark
    - snowflake.snowpark._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.snowflake.com/
  summary: Snowflake Snowpark for Python
  dev_url: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sfc-gh-nkumar
    - sfc-gh-jdu
    - sfc-gh-yzou
    - sfc-gh-yuwang
    - sfc-gh-aling
    - sfc-gh-aalam
    - sfc-gh-yixie
    - sfc-gh-achandrasekaran
    - sfc-gh-mkeller
