{% set name = "snowflake-snowpark-python" %}
{% set version = "1.43.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 282afccb8ba60289a263a42f3040b762c216eef4e64a3aea08ad7dda98a07dff

build:
  skip: true  # [py<38 or py>313]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools >=40.6.0
    - wheel
    # Snowpark IR
    - protobuf ==3.20.1  # [py<=310]
    - protobuf ==4.25.3  # [py>310]
    - mypy-protobuf
  run:
    - python
    - setuptools >=40.6.0
    - wheel
    - cloudpickle >=1.6.0,<=3.1.1,!=2.1.0,!=2.2.0
    - snowflake-connector-python >=3.16.0,<5.0.0  # 3.17 is not available in conda-forge yet
    - typing-extensions >=4.1.0,<5.0.0
    - pyyaml
    - protobuf >=3.20,<6.32
    - python-dateutil
    - tzlocal
  run_constrained:
    # Snowpark pandas
    - modin >=0.36.0,<0.38.0

test:
  imports:
    - snowflake.snowpark
    - snowflake.snowpark._internal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.snowflake.com/
  summary: Snowflake Snowpark for Python
  dev_url: https://github.com/snowflakedb/snowpark-python
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - sfc-gh-joshi
    - sfc-gh-jrose
    - sfc-gh-lmukhopadhyay
    - sfc-gh-nkumar
    - sfc-gh-jdu
    - sfc-gh-aling
    - sfc-gh-aalam
    - sfc-gh-yixie
    - sfc-gh-mkeller
    - sfc-gh-yuwang
